export const deals = {
  count: 2,
  next: null,
  previous: null,
  results: [
    {
      id: 1,
      listing: 1,
      date: '2001-01-01T14:32:00Z',
      project_type: 'choice_1',
      customer: {
        id: 1,
        user: {
          id: 501,
          wp_user_id: null,
          username: 'sngguojie@gmail.com',
          email: 'sngguojie@gmail.com',
          long_first_name: 'Guo Jie Sng',
          long_last_name: '',
          phone_number: '92961592',
          send_bird_access_token: '45fe94560aa7978b2f53ca7879077b76f93dc535',
          enable_chat: true,
          profile_image:
            'https://sghomeneeds-gallery.s3.amazonaws.com/-C5v2NWmEB38/AAAAAAAAAAI/AAAAAAAAAAA/AKxrwcYZgHI0GyGnuvqyJaTBIF27ePmbHw/s96-c/photo.jpg',
          merchant: [],
          consumer: [1],
          is_email_activated: false,
          is_deactivated: true,
          notification_settings: {
            emailArticlesAndNews: true,
            'emailPromotions&Tips': true,
            textChatNotifications: true,
            emailChatNotifications: true,
            emailNewProjectReviews: true,
          },
          emailArticlesAndNews: true,
          emailPromotionsTips: true,
          textChatNotifications: true,
          emailChatNotifications: true,
          emailNewProjectReviews: true,
        },
        created_at: '2018-12-26T19:28:40.217608Z',
        favourite_listings: [
          'nouve-home-services',
          'vimbox-movers',
          'the-plumbing-company',
          'home-carely-cleaning-services',
          'kiasu-plumber',
        ],
        favourite_galleries: [],
      },
      invoice_amount_dollars: '100.00',
      percent_commission: '10.00',
    },
    {
      id: 2,
      listing: 1,
      date: '2001-02-12T11:11:00Z',
      project_type: 'choice_1',
      customer: {
        id: 1,
        user: {
          id: 501,
          wp_user_id: null,
          username: 'sngguojie@gmail.com',
          email: 'sngguojie@gmail.com',
          long_first_name: 'Guo Jie Sng',
          long_last_name: '',
          phone_number: '92961592',
          send_bird_access_token: '45fe94560aa7978b2f53ca7879077b76f93dc535',
          enable_chat: true,
          profile_image:
            'https://sghomeneeds-gallery.s3.amazonaws.com/-C5v2NWmEB38/AAAAAAAAAAI/AAAAAAAAAAA/AKxrwcYZgHI0GyGnuvqyJaTBIF27ePmbHw/s96-c/photo.jpg',
          merchant: [],
          consumer: [1],
          is_email_activated: false,
          is_deactivated: true,
          notification_settings: {
            emailArticlesAndNews: true,
            'emailPromotions&Tips': true,
            textChatNotifications: true,
            emailChatNotifications: true,
            emailNewProjectReviews: true,
          },
          emailArticlesAndNews: true,
          emailPromotionsTips: true,
          textChatNotifications: true,
          emailChatNotifications: true,
          emailNewProjectReviews: true,
        },
        created_at: '2018-12-26T19:28:40.217608Z',
        favourite_listings: [
          'nouve-home-services',
          'vimbox-movers',
          'the-plumbing-company',
          'home-carely-cleaning-services',
          'kiasu-plumber',
        ],
        favourite_galleries: [],
      },
      invoice_amount_dollars: '100.00',
      percent_commission: '12.00',
    },
  ],
};
